version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: dannamo_db_container
    restart: always
    environment:
      POSTGRES_DB: dannamo_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    #networks:
    #  - my_network

#networks:
#  my_network:



# FONTI

# Per la creazione del container dall'immagine di postgres
# https://dsysd-dev.medium.com/setting-up-your-own-postgres-database-using-docker-container-b46e5ee22d3a

# Per la creazione automatica del db tramite file .sql
# https://stackoverflow.com/questions/75246059/create-a-postgres-database-within-a-docker-compose-yml-file

# ALTRO
# https://hackernoon.com/using-postgres-effectively-in-spring-boot-applications