
services:
  postgres_main:
    container_name: 'postgres_main'
    image: 'postgres:17.1'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_main:/var/lib/postgresql/data_main
    networks:
      - spring_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5


  postgres_cities:
    container_name: 'postgres_cities'
    image: 'postgres:17.1'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_cities:/var/lib/postgresql/data_cities
    networks:
      - spring_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_main:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      postgres_main:
        condition: service_healthy
      postgres_cities:
        condition: service_healthy
    networks:
      - spring_net
      - frontend_net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Evita che node_modules venga sovrascritto dal volume
    environment:
      - CHOKIDAR_USEPOLLING=true  # Utilizza il polling per la rilevazione dei cambiamenti nei file
    networks:
      - frontend_net

networks:
  spring_net:
  frontend_net:

volumes:
  postgres_data_main:
  postgres_data_cities: